### ISSUE TITLE
The skin fatals in 1.43

### ISSUE THREAD

**Issue by jdlrobson** [AWikia/SkinEvelution#118]
Hi just reporting the skin fatals in MediaWiki 1.43.
Patch incoming!

**Comment by HM100** [comment]
Which branch are you using. Does the ``main`` branch work in 1.43? If not, then send a PR for that branch please. The ``REL1_XX`` branches like ``REL1_37`` must support the target MW version

**Comment by HM100** [comment]
Fixed up 1.42 support on ``main`` branch again

**Comment by HM100** [comment]
Issue fixed
