### ISSUE TITLE
Missing release branches

### ISSUE THREAD

**Issue by noloader** [AWikia/SkinEvelution#24]
Hi Everyone,

This is a small request that will prove useful in the future.

We are testing Evelution. We use a Git clone to ensure we are up to date (we have a maintenance script that does a daily pull). It also avoids a Wget fetch and unpacking a ZIP or tarball. The script also checks out the branch that coincides with out Mediawiki version, which is currently MW 1.36.

Wikipedia creates branches for each release. For example, most extensions and skins have a `REL1_32`, `REL1_33`, `REL1_34`, `REL1_35`, `REL1_36` branch to support different Mediawiki releases. We noticed Evelution does not use Mediawiki's branching conventions.

The branches are very helpful in managing deprecated functions. For example, `BaseTemplate::getFooter` was deprecated at MW 1.35. The `REL1_35`, `REL1_36` branches can be changed to avoid calls to `BaseTemplate::getFooter`, while the older branches don't need a change. If the warnings are not managed, then they show up in the UI when a page is loaded.

It may be a good idea to start thinking about adding the standard mediawiki branches.

**Comment by HM100** [comment]
Evelution uses the ``main`` branch and it works with both MW 1.36 and MW 1.37. Evelution does not support MW 1.35.

As such, it does not use MW branching conventions at the moment and the PHP uses are minimal but this can be considered for the future. In the future, I may also drop out older MW versions from Evelution but it is not a priority now.

**Comment by HM100** [comment]
Done some minor changes to https://github.com/AWikia/SkinEvelution/blob/main/docs/index.md to clarify that the ``main`` branch works with both 1.36 and 1.37

**Comment by RhinosF1** [comment]
See also mediawiki.org

**Comment by HM100** [comment]
Noloader, if you want to continue using Evelution, you have to upgrade MW on Crpyto++ wiki you have to MW 1.37. Latest Evelution will not run on EOL releases of MW

**Comment by RhinosF1** [comment]
> Noloader, if you want to continue using Evelution, you have to upgrade MW on Crpyto++ wiki you have to MW 1.37. Latest Evelution will not run on EOL releases of MW

1.35 is not EOL @HM100

**Comment by HM100** [comment]
1.35 has never been supported by Evelution anyways due to limited Mustache Support

**Comment by noloader** [comment]
@[HM100](https://github.com/HM100),

Thanks for the heads up.

Yeah, I got a error when performing maintenance yesterday. I just removed Evelution from the wiki installation.

Thanks again.

**Comment by HM100** [comment]
> @[HM100](https://github.com/HM100),
> 
> Thanks for the heads up.
> 
> Yeah, I got a error when performing maintenance yesterday. I just removed Evelution from the wiki installation.
> 
> Thanks again.

I've re-enabled Evelution for 1.36 wikis but it shows up a deprecation warning as 1.36 support won't be kept for long
