### ISSUE TITLE
Avoid both list of messages & directory in skin.json

### ISSUE THREAD

**Issue by RhinosF1** [AWikia/SkinEvelution#26]
Unneeded

**Comment by HM100** [comment]
This surely needs a workaround in order for this issue to be solved. Pinning it and high priority

**Comment by HM100** [comment]
This can't be avoided as not [another skin](https://github.com/lakejason0/mediawiki-skins-Lakeus) does virtually the same but also appears to be a limitation of Mustache skin templating (I tested it today)
