### ISSUE TITLE
Implement Security & Contributing policies

### ISSUE THREAD

**Issue by RhinosF1** [AWikia/SkinEvelution#29]

**Comment by HM100** [comment]
In progress

**Comment by HM100** [comment]
Has been done. Only the latest seasonal (Major) release will be supported

**Comment by HM100** [comment]
To report security issues, use [this form](https://github.com/AWikia/SkinEvelution/security/advisories/new)

**Comment by HM100** [comment]
One can send issues by [emailing me at MW.org](https://www.mediawiki.org/wiki/Special:EmailUser/Giorgos456) as well
